[tool.poetry]
name = "html-parsing"
version = "0.1.0"
description = ""
authors = ["CPR Tech <tech@climatepolicyradar.org>"]

[tool.poetry.dependencies]
python = "^3.8"
awscli = "1.25.69"
news-please = "^1.5.22"
pandas = "^1.4.4"
tqdm = "^4.64.1"
pydantic = "^1.10.2"
click = "^8.1.3"
langdetect = "^1.0.9"
playwright = "^1.25.2"
readability-lxml = "^0.8.1"
bleach = "^5.0.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.20.0"
pyright = "^1.1.270"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
